runtime: php
env: flex

runtime_config: 
  document_root: public

skip_files:
  - ^node_modules/.*$
  - .env
  - .git
  - .gitignore
  - vendor/.*$

env_variables:
  ## Put production environment variables here.
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:nesNO3dR9jnrgBJb2O4R3bN48wRdzH8Idv2cZ42IngU=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: 35.222.185.209 
  DB_DATABASE: writers
  DB_USERNAME: amgaa
  DB_PASSWORD: Maximusprime09!
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/writers-mn:us-central1:free-writers"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"

beta_settings: 
  cloud_sql_instances: "writers-mn:us-central1:free-writers"
